apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-dev
  labels:
    app: web-bad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-bad
  template:
    metadata:
      labels:
        app: web-bad
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # <--- ĐÂY LÀ LỖI (Dùng tag latest)
