apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: pod-security-nonroot-no-privileged
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-runasnonroot
      match:
        resources:
          kinds: ["Pod"]
          namespaceSelector:
            matchExpressions:
              - key: policy.tier
                operator: Exists
      preconditions:
        any:
          - key: "{{ request.namespaceLabels.\"policy.tier\" || '' }}"
            operator: NotEquals
            value: "system"
          - key: "{{ request.object.metadata.labels.\"policy.allow-root\" || '' }}"
            operator: NotEquals
            value: "true"
      validate:
        message: "Pod phải khai báo spec.securityContext.runAsNonRoot=true (Tier 'system' cần label 'policy.allow-root: \"true\"' để bypass)"
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true

    - name: disallow-privileged
      match:
        resources:
          kinds: ["Pod"]
          namespaceSelector:
            matchExpressions:
              - key: policy.tier
                operator: Exists
      preconditions:
        any:
          - key: "{{ request.namespaceLabels.\"policy.tier\" || '' }}"
            operator: NotEquals
            value: "system"
          - key: "{{ request.object.metadata.labels.\"policy.allow-privileged\" || '' }}"
            operator: NotEquals
            value: "true"
      validate:
        message: "Không cho phép container chạy privileged=true (Tier 'system' cần label 'policy.allow-privileged: \"true\"' để bypass)"
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.privileged || false }}"
                    operator: Equals
                    value: true
          - list: "request.object.spec.initContainers || `[]`"
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.privileged || false }}"
                    operator: Equals
                    value: true
