apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: pod-security-nonroot-no-privileged
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    # 1. Require runAsNonRoot
    # Bypass bằng cách gán label cho namespace: policy.kyverno.io/allow-root="true"
    - name: require-runasnonroot
      match:
        resources:
          kinds: ["Pod"]
      exclude:
        resources:
          namespaces: ["kube-system", "kyverno", "argocd"]
      preconditions:
        all:
          - key: "{{ request.namespaceLabels.\"policy.kyverno.io/allow-root\" || 'false' }}"
            operator: NotEquals
            value: "true"
      validate:
        message: "Pod phải khai báo spec.securityContext.runAsNonRoot=true (Cần ns label policy.kyverno.io/allow-root='true' để bypass)"
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true

    # 2. Disallow privileged
    # Bypass bằng cách gán label cho namespace: policy.kyverno.io/allow-privileged="true"
    - name: disallow-privileged
      match:
        resources:
          kinds: ["Pod"]
      exclude:
        resources:
          namespaces: ["kube-system", "kyverno", "argocd"]
      preconditions:
        all:
          - key: "{{ request.namespaceLabels.\"policy.kyverno.io/allow-privileged\" || 'false' }}"
            operator: NotEquals
            value: "true"
      validate:
        message: "Không cho phép container chạy privileged=true (Cần ns label policy.kyverno.io/allow-privileged='true' để bypass)"
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.privileged || false }}"
                    operator: Equals
                    value: true
          - list: "request.object.spec.initContainers"
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.privileged || false }}"
                    operator: Equals
                    value: true
