apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: pod-security-nonroot-no-privileged
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-runasnonroot
      match:
        resources:
          kinds: ["Pod"]
      exclude:
        resources:
          namespaces: ["kube-system", "kyverno", "argocd"]
      preconditions:
        all:
          - key: "{{ request.namespaceLabels.\"policy.kyverno.io/allow-root\" || 'false' }}"
            operator: NotEquals
            value: "true"
      validate:
        message: "Access Denied: Container bắt buộc phải chạy với quyền non-root."
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true

    - name: disallow-privileged
      match:
        resources:
          kinds: ["Pod"]
      exclude:
        resources:
          namespaces: ["kube-system", "kyverno", "argocd"]
      preconditions:
        all:
          - key: "{{ request.namespaceLabels.\"policy.kyverno.io/allow-privileged\" || 'false' }}"
            operator: NotEquals
            value: "true"
      validate:
        message: "Access Denied: Không cho phép chạy mode Privileged."
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.privileged || false }}"
                    operator: Equals
                    value: true
          - list: "request.object.spec.initContainers"
            deny:
              conditions:
                any:
                  - key: "{{ element.securityContext.privileged || false }}"
                    operator: Equals
                    value: true
