apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: unique-ingress-host
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: check-unique-host
      match:
        resources:
          kinds:
            - Ingress

      context:
        - name: all_hosts
          apiCall:
            urlPath: "/networking.k8s.io/v1/ingresses"
            # Lấy tất cả host của các Ingress khác (không phải chính nó)
            jmesPath: "items[?!(metadata.name=='{{request.object.metadata.name}}' && metadata.namespace=='{{request.object.metadata.namespace}}')].spec.rules[].host"

      validate:
        message: "Domain này đã được sử dụng bởi Ingress khác trong cluster."
        foreach:
          - list: "request.object.spec.rules[].host"
            deny:
              conditions:
                all:
                  - key: "{{ element }}"
                    operator: In
                    value: "{{ all_hosts }}"
