apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: unique-ingress-host
spec:
  validationFailureAction: Enforce
  background: false # Bắt buộc false để gọi API Server realtime
  rules:
    - name: check-unique-host
      match:
        resources:
          kinds: ["Ingress"]
      context:
        - name: all_hosts
          apiCall:
            urlPath: "/networking.k8s.io/v1/ingresses"
            # [FIX] Lọc bỏ UID hiện tại và làm phẳng mảng host
            jmesPath: "items[?metadata.uid!='{{request.object.metadata.uid}}'].spec.rules[].host | []"
      validate:
        message: "Domain này đã được sử dụng bởi App khác. Vui lòng kiểm tra lại."
        foreach:
          - list: "request.object.spec.rules[].host"
            deny:
              conditions:
                all:
                  - key: "{{ element }}"
                    operator: AnyIn
                    value: "{{ all_hosts }}"
