apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: unique-ingress-host
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: check-unique-host
      match:
        resources:
          kinds: ["Ingress"]
          namespaceSelector:
            matchExpressions:
              - key: policy.tier
                operator: Exists
      context:
        - name: all_hosts
          apiCall:
            urlPath: "/apis/networking.k8s.io/v1/ingresses"
            jmesPath: "items[?metadata.uid!='{{request.object.metadata.uid}}'].spec.rules[].host | []"
      validate:
        message: "Domain này đã được sử dụng bởi App khác."
        foreach:
          - list: "request.object.spec.rules[].host"
            deny:
              conditions:
                all:
                  - key: "{{ element }}"
                    operator: AnyIn
                    value: "{{ all_hosts }}"
